language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  # /usr/bin/gcc points to an older compiler on both Linux and macOS.
  #- if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
  #- echo ${CC}
  - echo ${CXX}
  - ${CXX} --version

script:
  #- cmake .
  - make
